### ISSUE TITLE
Multiples id

### ISSUE THREAD

**Issue by linkstrifer** [galvisortiz/proyecto-makeitreal#1]
https://github.com/galvisortiz/proyecto-makeitreal/blob/f78d6aa2730c0030b8f621a0b07d192d21df1783/index.html#L13-L20

No estoy seguro para que le pones `ID`, pero los `ID` deberian ser unicos por pagina, en este caso quieres usarlos para aplicar los mismos estilos en multiples elementos, usa una clase, para eso son

**Comment by galvisortiz** [comment]
los cambie por una clase
